#include <stdio.h>   // FILE

/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum yytokentype {
      PUBLIC = 258,
      PRIVATE = 259,
      PROTECTED = 260,
      STATIC = 261,
      NAME = 262,
      INT_TYPE = 263,
      STRING_TYPE = 264,
      STRING_ARRAY_TYPE = 265,
      BOOLEAN_TYPE = 266,
      VOID_TYPE = 267,
      IMPLEMENTS = 268,
      EXTENDS = 269,
      CLASS = 270,
      INTERFACE = 271,
      IF = 272,
      WHILE = 273,
      STRING = 274,
      BOOLEAN = 275,
      OPERATOR = 276,
      RETURN = 47,
      INT = 277,
      LEFT_CURLY_BRACKET = 278,
      RIGHT_CURLY_BRACKET = 279,  
      LEFT_ROUND_BRACKET = 280,
      RIGHT_ROUND_BRACKET = 281,
      SEMICOLON = 282,
      DOT = 283,
   };
#endif
/* Tokens.  */
#define PUBLIC 258
#define PRIVATE 259
#define PROTECTED 260
#define STATIC 261
#define NAME 262
#define INT_TYPE 263
#define STRING_TYPE 264
#define STRING_ARRAY_TYPE 265
#define BOOLEAN_TYPE 266
#define VOID_TYPE 267
#define IMPLEMENTS 268
#define EXTENDS 269
#define CLASS 270
#define INTERFACE 271
#define IF 272
#define WHILE 273
#define STRING 274
#define BOOLEAN 275
#define OPERATOR 276
#define RETURN 47
#define INT 277
#define LEFT_CURLY_BRACKET 278
#define RIGHT_CURLY_BRACKET 279
#define LEFT_ROUND_BRACKET 280
#define RIGHT_ROUND_BRACKET 281
#define SEMICOLON 282
#define DOT 283

// Public functions generated by Flex
void yyset_in (FILE * in_str);
char *yyget_text (void);
int yylex ();